version: "3.8"

services:
  rag-app:
    build: .
    container_name: rag-final-report-prod
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - APP_HOST=0.0.0.0
      - APP_PORT=5002
    env_file:
      - .env
    volumes:
      # 只掛載必要的目錄
      - ./data:/app/data
      - ./static:/app/static
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"
        reservations:
          memory: 512M
          cpus: "0.25"
    networks:
      - rag-network-prod

  # 可選：Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: rag-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rag-app
    restart: unless-stopped
    networks:
      - rag-network-prod

networks:
  rag-network-prod:
    driver: bridge

volumes:
  logs:
